// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroEstudiantil.Infrastructure.Data;

#nullable disable

namespace RegistroEstudiantil.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250913140141_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegistroEstudiantil.Domain.Entities.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Estudiantes", (string)null);
                });

            modelBuilder.Entity("RegistroEstudiantil.Domain.Entities.GrupoClase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(40);

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<string>("NombreGrupo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfesorId");

                    b.HasIndex("MateriaId", "ProfesorId", "Periodo", "NombreGrupo")
                        .IsUnique()
                        .HasFilter("[NombreGrupo] IS NOT NULL");

                    b.ToTable("Grupos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cupo = 40,
                            MateriaId = 1,
                            NombreGrupo = "A",
                            Periodo = "2025-2",
                            ProfesorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cupo = 40,
                            MateriaId = 2,
                            NombreGrupo = "A",
                            Periodo = "2025-2",
                            ProfesorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cupo = 40,
                            MateriaId = 3,
                            NombreGrupo = "A",
                            Periodo = "2025-2",
                            ProfesorId = 2
                        },
                        new
                        {
                            Id = 4,
                            Cupo = 40,
                            MateriaId = 4,
                            NombreGrupo = "A",
                            Periodo = "2025-2",
                            ProfesorId = 2
                        },
                        new
                        {
                            Id = 5,
                            Cupo = 40,
                            MateriaId = 5,
                            NombreGrupo = "A",
                            Periodo = "2025-2",
                            ProfesorId = 3
                        },
                        new
                        {
                            Id = 6,
                            Cupo = 40,
                            MateriaId = 6,
                            NombreGrupo = "A",
                            Periodo = "2025-2",
                            ProfesorId = 3
                        },
                        new
                        {
                            Id = 7,
                            Cupo = 40,
                            MateriaId = 7,
                            NombreGrupo = "A",
                            Periodo = "2025-2",
                            ProfesorId = 4
                        },
                        new
                        {
                            Id = 8,
                            Cupo = 40,
                            MateriaId = 8,
                            NombreGrupo = "A",
                            Periodo = "2025-2",
                            ProfesorId = 4
                        },
                        new
                        {
                            Id = 9,
                            Cupo = 40,
                            MateriaId = 9,
                            NombreGrupo = "A",
                            Periodo = "2025-2",
                            ProfesorId = 5
                        },
                        new
                        {
                            Id = 10,
                            Cupo = 40,
                            MateriaId = 10,
                            NombreGrupo = "A",
                            Periodo = "2025-2",
                            ProfesorId = 5
                        });
                });

            modelBuilder.Entity("RegistroEstudiantil.Domain.Entities.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrupoClaseId")
                        .HasColumnType("int");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoClaseId");

                    b.HasIndex("EstudianteId", "GrupoClaseId")
                        .IsUnique();

                    b.ToTable("Inscripciones", (string)null);
                });

            modelBuilder.Entity("RegistroEstudiantil.Domain.Entities.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Creditos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Materias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "MAT101",
                            Creditos = 3,
                            Nombre = "Matemáticas I"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "PRO101",
                            Creditos = 3,
                            Nombre = "Programación I"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "BD101",
                            Creditos = 3,
                            Nombre = "Bases de Datos"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "ING101",
                            Creditos = 3,
                            Nombre = "Inglés I"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "FIS101",
                            Creditos = 3,
                            Nombre = "Física I"
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "EST101",
                            Creditos = 3,
                            Nombre = "Estadística"
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "RED101",
                            Creditos = 3,
                            Nombre = "Redes I"
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "SOF101",
                            Creditos = 3,
                            Nombre = "Ingeniería de Software"
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "SIS101",
                            Creditos = 3,
                            Nombre = "Sistemas Operativos"
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "ETI101",
                            Creditos = 3,
                            Nombre = "Ética Profesional"
                        });
                });

            modelBuilder.Entity("RegistroEstudiantil.Domain.Entities.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Profesores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "García",
                            Nombres = "Ana"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Pérez",
                            Nombres = "Luis"
                        },
                        new
                        {
                            Id = 3,
                            Apellidos = "López",
                            Nombres = "Marta"
                        },
                        new
                        {
                            Id = 4,
                            Apellidos = "Ramírez",
                            Nombres = "Carlos"
                        },
                        new
                        {
                            Id = 5,
                            Apellidos = "Torres",
                            Nombres = "Sofía"
                        });
                });

            modelBuilder.Entity("RegistroEstudiantil.Domain.Entities.ProfesorMateria", b =>
                {
                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.HasKey("ProfesorId", "MateriaId");

                    b.HasIndex("MateriaId");

                    b.ToTable("ProfesorMaterias", (string)null);

                    b.HasData(
                        new
                        {
                            ProfesorId = 1,
                            MateriaId = 1
                        },
                        new
                        {
                            ProfesorId = 1,
                            MateriaId = 2
                        },
                        new
                        {
                            ProfesorId = 2,
                            MateriaId = 3
                        },
                        new
                        {
                            ProfesorId = 2,
                            MateriaId = 4
                        },
                        new
                        {
                            ProfesorId = 3,
                            MateriaId = 5
                        },
                        new
                        {
                            ProfesorId = 3,
                            MateriaId = 6
                        },
                        new
                        {
                            ProfesorId = 4,
                            MateriaId = 7
                        },
                        new
                        {
                            ProfesorId = 4,
                            MateriaId = 8
                        },
                        new
                        {
                            ProfesorId = 5,
                            MateriaId = 9
                        },
                        new
                        {
                            ProfesorId = 5,
                            MateriaId = 10
                        });
                });

            modelBuilder.Entity("RegistroEstudiantil.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Estudiante");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("RegistroEstudiantil.Domain.Entities.Estudiante", b =>
                {
                    b.HasOne("RegistroEstudiantil.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Estudiante")
                        .HasForeignKey("RegistroEstudiantil.Domain.Entities.Estudiante", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RegistroEstudiantil.Domain.Entities.GrupoClase", b =>
                {
                    b.HasOne("RegistroEstudiantil.Domain.Entities.Materia", "Materia")
                        .WithMany("Grupos")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistroEstudiantil.Domain.Entities.Profesor", "Profesor")
                        .WithMany("Grupos")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("RegistroEstudiantil.Domain.Entities.Inscripcion", b =>
                {
                    b.HasOne("RegistroEstudiantil.Domain.Entities.Estudiante", "Estudiante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistroEstudiantil.Domain.Entities.GrupoClase", "GrupoClase")
                        .WithMany("Inscripciones")
                        .HasForeignKey("GrupoClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("GrupoClase");
                });

            modelBuilder.Entity("RegistroEstudiantil.Domain.Entities.ProfesorMateria", b =>
                {
                    b.HasOne("RegistroEstudiantil.Domain.Entities.Materia", "Materia")
                        .WithMany("ProfesorMaterias")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistroEstudiantil.Domain.Entities.Profesor", "Profesor")
                        .WithMany("ProfesorMaterias")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("RegistroEstudiantil.Domain.Entities.Estudiante", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("RegistroEstudiantil.Domain.Entities.GrupoClase", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("RegistroEstudiantil.Domain.Entities.Materia", b =>
                {
                    b.Navigation("Grupos");

                    b.Navigation("ProfesorMaterias");
                });

            modelBuilder.Entity("RegistroEstudiantil.Domain.Entities.Profesor", b =>
                {
                    b.Navigation("Grupos");

                    b.Navigation("ProfesorMaterias");
                });

            modelBuilder.Entity("RegistroEstudiantil.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Estudiante");
                });
#pragma warning restore 612, 618
        }
    }
}



